import uuid
import requests

from milestone2.utils import get_abdm_timestamp, get_abdm_access_token

def update_bridge_url_service(target_url: str) -> tuple[dict, int]:
    api_url = "https://dev.abdm.gov.in/api/hiecm/gateway/v3/bridge/url"

    # ✅ Magically fetch the token generated by your Auth API!
    access_token = get_abdm_access_token()
    
    if not access_token:
        return {"error": "Gateway token missing. Please run the Auth Token API first."}, 401

    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {access_token}",
        "REQUEST-ID": str(uuid.uuid4()),
        "TIMESTAMP": get_abdm_timestamp(),
        "X-CM-ID": "sbx"
    }

    payload = {
        "url": target_url
    }

    try:
        # Note: The documentation specifies this is a PATCH request, not POST
        res = requests.patch(api_url, headers=headers, json=payload)
        
        # ABDM 202 Accepted responses sometimes have empty bodies
        if res.text:
            return res.json(), res.status_code
        return {"message": "Bridge URL updated successfully"}, res.status_code
        
    except requests.exceptions.RequestException as e:
        return {"error": "Failed to connect to ABDM", "details": str(e)}, 503